version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: eristic-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_PATH=/app/database/eristic.db
    volumes:
      - db_data:/app/database
    ports:
      - "3001:3001"
    networks:
      - eristic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eristic-frontend
    environment:
      - BACKEND_URL=http://backend:3001
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - eristic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db_data:
    driver: local

networks:
  eristic-network:
    driver: bridge