[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
httpPath = "/health"
httpTimeout = 10

[deploy.resources]
memoryLimit = "512Mi"
cpuLimit = "500m"